
-- MASSIVE CURRICULUM UPDATE FOR FLUENTYAPP (35 LESSONS)
-- Delete existing exercises to avoid duplication
DELETE FROM public.exercises;

-- Insert 350+ Questions
INSERT INTO public.exercises (lesson_id, type, question, options, correct_answer) VALUES
('basics-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Anak laki-laki"', '["Girl","Man","Boy","Woman"]'::jsonb, 'Boy'),
('basics-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Anak perempuan"', '["Girl","Man","Boy","Woman"]'::jsonb, 'Girl'),
('basics-1', 'WORD_BANK', 'Terjemahkan: "Saya seorang pria"', '["I","am","a","man","woman","boy"]'::jsonb, 'I am a man'),
('basics-1', 'WORD_BANK', 'Terjemahkan: "Dia (perempuan) makan apel"', '["She","He","eats","eat","an","apple"]'::jsonb, 'She eats an apple'),
('basics-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya minum air"', null, 'I drink water'),
('basics-1', 'MULTIPLE_CHOICE', 'Pilih kata yang hilang: "___ is a woman"', '["She","He","It","I"]'::jsonb, 'She'),
('basics-1', 'WORD_BANK', 'Terjemahkan: "Kamu adalah seorang anak laki-laki"', '["You","are","is","a","boy","girl"]'::jsonb, 'You are a boy'),
('basics-1', 'WORD_BANK', 'Terjemahkan: "Pria itu minum air"', '["The","A","man","woman","drinks","water"]'::jsonb, 'The man drinks water'),
('basics-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Dia (laki-laki) makan"', null, 'He eats'),
('basics-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Roti"', '["Bread","Water","Apple","Milk"]'::jsonb, 'Bread'),
('basics-2', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Buku"', '["Newspaper","Book","Letter","Menu"]'::jsonb, 'Book'),
('basics-2', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Koran"', '["Book","Newspaper","Word","Pen"]'::jsonb, 'Newspaper'),
('basics-2', 'WORD_BANK', 'Terjemahkan: "Saya membaca buku"', '["I","am","read","a","book","the"]'::jsonb, 'I read a book'),
('basics-2', 'WORD_BANK', 'Terjemahkan: "Mereka membaca koran"', '["They","We","read","reads","a","newspaper"]'::jsonb, 'They read a newspaper'),
('basics-2', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kami memiliki apel"', null, 'We have apples'),
('basics-2', 'MULTIPLE_CHOICE', 'Pilih kata yang hilang: "___ write a letter"', '["I","She","He","It"]'::jsonb, 'I'),
('basics-2', 'WORD_BANK', 'Terjemahkan: "Anak-anak itu membaca buku"', '["The","children","child","read","reads","books"]'::jsonb, 'The children read books'),
('basics-2', 'WORD_BANK', 'Terjemahkan: "Kamu membaca menu"', '["You","read","reads","a","the","menu"]'::jsonb, 'You read the menu'),
('basics-2', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Dia (perempuan) memiliki sebuah buku"', null, 'She has a book'),
('basics-2', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Susu"', '["Water","Coffee","Milk","Tea"]'::jsonb, 'Milk'),
('phrases-1', 'MULTIPLE_CHOICE', 'Apa arti dari "Hello"?', '["Selamat tinggal","Halo","Terima kasih","Maaf"]'::jsonb, 'Halo'),
('phrases-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Selamat pagi"', '["Good night","Good afternoon","Good morning","Goodbye"]'::jsonb, 'Good morning'),
('phrases-1', 'WORD_BANK', 'Terjemahkan: "Terima kasih banyak"', '["Thank","you","very","much","please","sorry"]'::jsonb, 'Thank you very much'),
('phrases-1', 'WORD_BANK', 'Terjemahkan: "Sama-sama"', '["You","are","welcome","sorry","thank","much"]'::jsonb, 'You are welcome'),
('phrases-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Maaf"', null, 'Sorry'),
('phrases-1', 'MULTIPLE_CHOICE', 'Pilih respons yang tepat untuk "How are you?"', '["I am a boy","I am fine, thank you","Good morning","Goodbye"]'::jsonb, 'I am fine, thank you'),
('phrases-1', 'WORD_BANK', 'Terjemahkan: "Permisi, di mana toiletnya?"', '["Excuse","me,","where","is","the","restroom?"]'::jsonb, 'Excuse me, where is the restroom?'),
('phrases-1', 'WORD_BANK', 'Terjemahkan: "Selamat malam"', '["Good","evening","night","morning","afternoon"]'::jsonb, 'Good evening'),
('phrases-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Sampai jumpa besok"', null, 'See you tomorrow'),
('phrases-1', 'MULTIPLE_CHOICE', 'Apa arti dari "Please"?', '["Maaf","Tolong","Terima kasih","Sama-sama"]'::jsonb, 'Tolong'),
('food-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Ayam"', '["Beef","Fish","Chicken","Pork"]'::jsonb, 'Chicken'),
('food-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Nasi"', '["Noodles","Rice","Bread","Potato"]'::jsonb, 'Rice'),
('food-1', 'WORD_BANK', 'Terjemahkan: "Saya makan sarapan"', '["I","eat","breakfast","dinner","lunch"]'::jsonb, 'I eat breakfast'),
('food-1', 'WORD_BANK', 'Terjemahkan: "Dia suka buah jeruk"', '["He","likes","oranges","apple","banana"]'::jsonb, 'He likes oranges'),
('food-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kami makan malam bersama"', null, 'We eat dinner together'),
('food-1', 'MULTIPLE_CHOICE', 'Pilih kata yang tepat: "I want a cup of ___"', '["Coffee","Meat","Rice","Egg"]'::jsonb, 'Coffee'),
('food-1', 'WORD_BANK', 'Terjemahkan: "Sup ini panas"', '["This","soup","is","hot","cold","sweet"]'::jsonb, 'This soup is hot'),
('food-1', 'WORD_BANK', 'Terjemahkan: "Bolehkah saya minta air?"', '["Can","I","have","some","water?","please"]'::jsonb, 'Can I have some water?'),
('food-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Telur goreng"', null, 'Fried egg'),
('food-1', 'MULTIPLE_CHOICE', 'Apa arti dari "Lunch"?', '["Sarapan","Makan Siang","Makan Malam","Cemilan"]'::jsonb, 'Makan Siang'),
('animals-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Kucing"', '["Dog","Cat","Bird","Fish"]'::jsonb, 'Cat'),
('animals-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Gajah"', '["Lion","Tiger","Elephant","Monkey"]'::jsonb, 'Elephant'),
('animals-1', 'WORD_BANK', 'Terjemahkan: "Anjing itu menggonggong"', '["The","dog","barks","meows","sleeps"]'::jsonb, 'The dog barks'),
('animals-1', 'WORD_BANK', 'Terjemahkan: "Burung itu terbang di langit"', '["The","bird","flies","in","the","sky"]'::jsonb, 'The bird flies in the sky'),
('animals-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya punya dua kucing"', null, 'I have two cats'),
('animals-1', 'MULTIPLE_CHOICE', 'Hewan mana yang hidup di air?', '["Fish","Monkey","Bird","Lion"]'::jsonb, 'Fish'),
('animals-1', 'WORD_BANK', 'Terjemahkan: "Singa adalah raja hutan"', '["The","lion","is","the","king","of","jungle"]'::jsonb, 'The lion is the king of the jungle'),
('animals-1', 'WORD_BANK', 'Terjemahkan: "Kuda berlari cepat"', '["Horses","run","fast","slow","jump"]'::jsonb, 'Horses run fast'),
('animals-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Monyet suka pisang"', null, 'Monkeys like bananas'),
('animals-1', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Ular"?', '["Snake","Lizard","Frog","Turtle"]'::jsonb, 'Snake'),
('plurals-1', 'MULTIPLE_CHOICE', 'Bentuk jamak dari "Book" adalah...', '["Bookes","Books","Book","Bookies"]'::jsonb, 'Books'),
('plurals-1', 'MULTIPLE_CHOICE', 'Bentuk jamak dari "Child" adalah...', '["Childs","Childrens","Children","Childes"]'::jsonb, 'Children'),
('plurals-1', 'WORD_BANK', 'Terjemahkan: "Banyak pria dan wanita"', '["Many","men","and","women","man","woman"]'::jsonb, 'Many men and women'),
('plurals-1', 'WORD_BANK', 'Terjemahkan: "Kucing-kucing itu sedang tidur"', '["The","cats","are","sleeping","cat","is"]'::jsonb, 'The cats are sleeping'),
('plurals-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Dua mobil"', null, 'Two cars'),
('plurals-1', 'MULTIPLE_CHOICE', 'Bentuk jamak dari "Mouse" adalah...', '["Mouses","Mice","Meese","Mooses"]'::jsonb, 'Mice'),
('plurals-1', 'WORD_BANK', 'Terjemahkan: "Daun-daun berguguran"', '["The","leaves","are","falling","leaf","is"]'::jsonb, 'The leaves are falling'),
('plurals-1', 'WORD_BANK', 'Terjemahkan: "Orang-orang sedang menunggu"', '["The","people","are","waiting","person","is"]'::jsonb, 'The people are waiting'),
('plurals-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Tiga kotak (boxes)"', null, 'Three boxes'),
('plurals-1', 'MULTIPLE_CHOICE', 'Bentuk jamak dari "Tooth" adalah...', '["Tooths","Teeth","Teeths","Toothes"]'::jsonb, 'Teeth'),
('adjectives-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Besar"', '["Small","Big","Tall","Short"]'::jsonb, 'Big'),
('adjectives-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Senang"', '["Sad","Angry","Happy","Tired"]'::jsonb, 'Happy'),
('adjectives-1', 'WORD_BANK', 'Terjemahkan: "Rumah yang indah"', '["A","beautiful","house","ugly","car"]'::jsonb, 'A beautiful house'),
('adjectives-1', 'WORD_BANK', 'Terjemahkan: "Pria tua itu kuat"', '["The","old","man","is","strong","weak"]'::jsonb, 'The old man is strong'),
('adjectives-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Ini adalah anjing kecil"', null, 'This is a small dog'),
('adjectives-1', 'MULTIPLE_CHOICE', 'Lawan kata dari "Fast" (Cepat) adalah...', '["Slow","Quick","Loud","Quiet"]'::jsonb, 'Slow'),
('adjectives-1', 'WORD_BANK', 'Terjemahkan: "Cuaca hari ini dingin"', '["The","weather","today","is","cold","hot"]'::jsonb, 'The weather today is cold'),
('adjectives-1', 'WORD_BANK', 'Terjemahkan: "Wanita yang pintar"', '["A","smart","woman","stupid","man"]'::jsonb, 'A smart woman'),
('adjectives-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Mobilnya mahal"', null, 'His car is expensive'),
('adjectives-1', 'MULTIPLE_CHOICE', 'Apa arti "Clean"?', '["Kotor","Bersih","Rapih","Berantakan"]'::jsonb, 'Bersih'),
('present-tense-1', 'MULTIPLE_CHOICE', 'Pilih kata yang tepat: "He ___ to school everyday"', '["go","goes","going","gone"]'::jsonb, 'goes'),
('present-tense-1', 'MULTIPLE_CHOICE', 'Pilih kata yang tepat: "I ___ coffee in the morning"', '["drinks","drinking","drink","drunk"]'::jsonb, 'drink'),
('present-tense-1', 'WORD_BANK', 'Terjemahkan: "Mereka bermain sepak bola"', '["They","play","football","plays","playing"]'::jsonb, 'They play football'),
('present-tense-1', 'WORD_BANK', 'Terjemahkan: "Dia (perempuan) belajar dengan giat"', '["She","studies","hard","study","learning"]'::jsonb, 'She studies hard'),
('present-tense-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kami tinggal di Jakarta"', null, 'We live in Jakarta'),
('present-tense-1', 'MULTIPLE_CHOICE', 'Kalimat negatif yang benar: "She ___ like apples"', '["don''''t","doesn''''t","isn''''t","aren''''t"]'::jsonb, 'doesn''t'),
('present-tense-1', 'WORD_BANK', 'Terjemahkan: "Apakah kamu berbicara bahasa Inggris?"', '["Do","you","speak","English?","Does"]'::jsonb, 'Do you speak English?'),
('present-tense-1', 'WORD_BANK', 'Terjemahkan: "Burung-burung bernyanyi di pagi hari"', '["The","birds","sing","in","the","morning"]'::jsonb, 'The birds sing in the morning'),
('present-tense-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya tidak tahu"', null, 'I do not know'),
('present-tense-1', 'MULTIPLE_CHOICE', 'Pilih kata yang tepat: "It ___ a lot in winter"', '["snow","snows","snowing","snowed"]'::jsonb, 'snows'),
('clothing-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Kemeja"', '["Pants","Shirt","Dress","Shoes"]'::jsonb, 'Shirt'),
('clothing-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan untuk "Sepatu"', '["Socks","Hat","Shoes","Jacket"]'::jsonb, 'Shoes'),
('clothing-1', 'WORD_BANK', 'Terjemahkan: "Saya memakai jaket"', '["I","am","wearing","a","jacket","shirt"]'::jsonb, 'I am wearing a jacket'),
('clothing-1', 'WORD_BANK', 'Terjemahkan: "Dia (perempuan) membeli gaun baru"', '["She","buys","a","new","dress","old"]'::jsonb, 'She buys a new dress'),
('clothing-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Celana panjang hitam"', null, 'Black pants'),
('clothing-1', 'MULTIPLE_CHOICE', 'Apa yang dikenakan di kepala?', '["Gloves","Socks","Hat","Belt"]'::jsonb, 'Hat'),
('clothing-1', 'WORD_BANK', 'Terjemahkan: "Tolong pakai sepatumu"', '["Please","put","on","your","shoes","take"]'::jsonb, 'Please put on your shoes'),
('clothing-1', 'WORD_BANK', 'Terjemahkan: "Kemejanya kebesaran"', '["His","shirt","is","too","big","small"]'::jsonb, 'His shirt is too big'),
('clothing-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kaus kaki merah"', null, 'Red socks'),
('clothing-1', 'MULTIPLE_CHOICE', 'Apa arti "Skirt"?', '["Celana pendek","Rok","Kemeja","Topi"]'::jsonb, 'Rok'),
('colors-1', 'MULTIPLE_CHOICE', 'Warna langit adalah...', '["Red","Green","Blue","Yellow"]'::jsonb, 'Blue'),
('colors-1', 'MULTIPLE_CHOICE', 'Warna rumput adalah...', '["Blue","Red","Green","Orange"]'::jsonb, 'Green'),
('colors-1', 'WORD_BANK', 'Terjemahkan: "Mobil itu berwarna merah"', '["The","car","is","red","blue","black"]'::jsonb, 'The car is red'),
('colors-1', 'WORD_BANK', 'Terjemahkan: "Saya suka gaun kuningmu"', '["I","like","your","yellow","dress","green"]'::jsonb, 'I like your yellow dress'),
('colors-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kucing hitam"', null, 'A black cat'),
('colors-1', 'MULTIPLE_CHOICE', 'Campuran merah dan putih menjadi...', '["Purple","Orange","Pink","Brown"]'::jsonb, 'Pink'),
('colors-1', 'WORD_BANK', 'Terjemahkan: "Rambutnya berwarna cokelat gelap"', '["Her","hair","is","dark","brown","light"]'::jsonb, 'Her hair is dark brown'),
('colors-1', 'WORD_BANK', 'Terjemahkan: "Awan putih di langit"', '["White","clouds","in","the","sky","black"]'::jsonb, 'White clouds in the sky'),
('colors-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Buku itu biru"', null, 'The book is blue'),
('colors-1', 'MULTIPLE_CHOICE', 'Apa warna matahari?', '["Yellow","Purple","Black","Grey"]'::jsonb, 'Yellow'),
('questions-1', 'MULTIPLE_CHOICE', 'Apa arti "Who"?', '["Apa","Di mana","Siapa","Kapan"]'::jsonb, 'Siapa'),
('questions-1', 'MULTIPLE_CHOICE', 'Apa arti "Where"?', '["Kapan","Mengapa","Bagaimana","Di mana"]'::jsonb, 'Di mana'),
('questions-1', 'WORD_BANK', 'Terjemahkan: "Apa ini?"', '["What","is","this?","that?","Who"]'::jsonb, 'What is this?'),
('questions-1', 'WORD_BANK', 'Terjemahkan: "Kenapa kamu menangis?"', '["Why","are","you","crying?","When","smiling"]'::jsonb, 'Why are you crying?'),
('questions-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kapan kamu datang?"', null, 'When are you coming?'),
('questions-1', 'MULTIPLE_CHOICE', 'Pilih kata yang tepat: "___ are you?" (Bagaimana kabarmu?)', '["What","Where","How","Who"]'::jsonb, 'How'),
('questions-1', 'WORD_BANK', 'Terjemahkan: "Di mana rumahmu?"', '["Where","is","your","house?","my","car"]'::jsonb, 'Where is your house?'),
('questions-1', 'WORD_BANK', 'Terjemahkan: "Siapa pria itu?"', '["Who","is","that","man?","woman?"]'::jsonb, 'Who is that man?'),
('questions-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Berapa banyak?"', null, 'How much?'),
('questions-1', 'MULTIPLE_CHOICE', 'Apa arti "Which"?', '["Yang mana","Berapa","Siapa","Mengapa"]'::jsonb, 'Yang mana'),
('prepositions-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Di dalam"', '["On","In","At","Under"]'::jsonb, 'In'),
('prepositions-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Di atas"', '["In","Under","On","Beside"]'::jsonb, 'On'),
('prepositions-1', 'WORD_BANK', 'Terjemahkan: "Kucing ada di bawah meja"', '["The","cat","is","under","the","table"]'::jsonb, 'The cat is under the table'),
('prepositions-1', 'WORD_BANK', 'Terjemahkan: "Bukunya ada di dalam tas"', '["The","book","is","in","the","bag"]'::jsonb, 'The book is in the bag'),
('prepositions-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya di rumah"', null, 'I am at home'),
('prepositions-1', 'MULTIPLE_CHOICE', 'Pilih kata yang tepat: "She sits ___ him"', '["between","beside","in","on"]'::jsonb, 'beside'),
('prepositions-1', 'WORD_BANK', 'Terjemahkan: "Berjalanlah melewati taman"', '["Walk","through","the","park","over"]'::jsonb, 'Walk through the park'),
('prepositions-1', 'WORD_BANK', 'Terjemahkan: "Mobil diparkir di belakang gedung"', '["The","car","is","parked","behind","the","building"]'::jsonb, 'The car is parked behind the building'),
('prepositions-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Di atas meja"', null, 'On the table'),
('prepositions-1', 'MULTIPLE_CHOICE', 'Apa arti "Between"?', '["Di depan","Di antara","Di belakang","Di sebelah"]'::jsonb, 'Di antara'),
('time-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Besok"', '["Yesterday","Today","Tomorrow","Tonight"]'::jsonb, 'Tomorrow'),
('time-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Senin"', '["Sunday","Tuesday","Monday","Friday"]'::jsonb, 'Monday'),
('time-1', 'WORD_BANK', 'Terjemahkan: "Jam berapa sekarang?"', '["What","time","is","it","now?","day"]'::jsonb, 'What time is it now?'),
('time-1', 'WORD_BANK', 'Terjemahkan: "Saya akan pergi hari Jumat"', '["I","will","go","on","Friday","Sunday"]'::jsonb, 'I will go on Friday'),
('time-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kemarin adalah hari Minggu"', null, 'Yesterday was Sunday'),
('time-1', 'MULTIPLE_CHOICE', 'Bulan pertama dalam setahun adalah...', '["February","January","March","December"]'::jsonb, 'January'),
('time-1', 'WORD_BANK', 'Terjemahkan: "Rapatnya jam 10 pagi"', '["The","meeting","is","at","10","AM"]'::jsonb, 'The meeting is at 10 AM'),
('time-1', 'WORD_BANK', 'Terjemahkan: "Tahun depan"', '["Next","year","Last","month","week"]'::jsonb, 'Next year'),
('time-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Malam ini"', null, 'Tonight'),
('time-1', 'MULTIPLE_CHOICE', 'Apa arti "Weekend"?', '["Hari kerja","Akhir pekan","Liburan","Bulan depan"]'::jsonb, 'Akhir pekan'),
('family-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Ibu"', '["Father","Sister","Mother","Aunt"]'::jsonb, 'Mother'),
('family-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Saudara laki-laki"', '["Brother","Uncle","Cousin","Son"]'::jsonb, 'Brother'),
('family-1', 'WORD_BANK', 'Terjemahkan: "Dia adalah ayahku"', '["He","is","my","father","mother","brother"]'::jsonb, 'He is my father'),
('family-1', 'WORD_BANK', 'Terjemahkan: "Kakek saya sudah tua"', '["My","grandfather","is","old","young","grandmother"]'::jsonb, 'My grandfather is old'),
('family-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya sayang keluarga saya"', null, 'I love my family'),
('family-1', 'MULTIPLE_CHOICE', 'Siapa saudara perempuan dari ibu/ayahmu?', '["Aunt","Niece","Sister","Cousin"]'::jsonb, 'Aunt'),
('family-1', 'WORD_BANK', 'Terjemahkan: "Mereka adalah sepupuku"', '["They","are","my","cousins","parents","siblings"]'::jsonb, 'They are my cousins'),
('family-1', 'WORD_BANK', 'Terjemahkan: "Paman saya tinggi"', '["My","uncle","is","tall","short","aunt"]'::jsonb, 'My uncle is tall'),
('family-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saudara perempuan"', null, 'Sister'),
('family-1', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Orang tua"?', '["Relatives","Parents","Family","Siblings"]'::jsonb, 'Parents'),
('jobs-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Dokter"', '["Nurse","Doctor","Teacher","Engineer"]'::jsonb, 'Doctor'),
('jobs-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Guru"', '["Student","Professor","Teacher","Pilot"]'::jsonb, 'Teacher'),
('jobs-1', 'WORD_BANK', 'Terjemahkan: "Dia bekerja sebagai insinyur"', '["He","works","as","an","engineer","doctor"]'::jsonb, 'He works as an engineer'),
('jobs-1', 'WORD_BANK', 'Terjemahkan: "Polisi itu sangat berani"', '["The","police","officer","is","very","brave"]'::jsonb, 'The police officer is very brave'),
('jobs-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya ingin menjadi artis"', null, 'I want to be an artist'),
('jobs-1', 'MULTIPLE_CHOICE', 'Siapa yang menerbangkan pesawat?', '["Driver","Sailor","Pilot","Mechanic"]'::jsonb, 'Pilot'),
('jobs-1', 'WORD_BANK', 'Terjemahkan: "Koki memasak makanan enak"', '["The","chef","cooks","delicious","food"]'::jsonb, 'The chef cooks delicious food'),
('jobs-1', 'WORD_BANK', 'Terjemahkan: "Petani bekerja di ladang"', '["The","farmer","works","in","the","field"]'::jsonb, 'The farmer works in the field'),
('jobs-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Perawat yang baik"', null, 'A kind nurse'),
('jobs-1', 'MULTIPLE_CHOICE', 'Apa arti "Writer"?', '["Penyanyi","Penulis","Pelukis","Aktor"]'::jsonb, 'Penulis'),
('travel-1', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Penerbangan"?', '["Train","Flight","Bus","Ship"]'::jsonb, 'Flight'),
('travel-1', 'MULTIPLE_CHOICE', 'Di mana Anda menunggu pesawat?', '["Gate","Platform","Stop","Station"]'::jsonb, 'Gate'),
('travel-1', 'WORD_BANK', 'Terjemahkan: "Boleh saya lihat paspor Anda?"', '["May","I","see","your","passport?","ticket"]'::jsonb, 'May I see your passport?'),
('travel-1', 'WORD_BANK', 'Terjemahkan: "Ke mana arah bandara?"', '["Which","way","to","the","airport?","station"]'::jsonb, 'Which way to the airport?'),
('travel-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Pesawat saya terlambat"', null, 'My flight is delayed'),
('travel-1', 'MULTIPLE_CHOICE', 'Apa yang Anda bawa saat bepergian?', '["House","Luggage","Car","Tree"]'::jsonb, 'Luggage'),
('travel-1', 'WORD_BANK', 'Terjemahkan: "Saya perlu memanggil taksi"', '["I","need","to","call","a","taxi","bus"]'::jsonb, 'I need to call a taxi'),
('travel-1', 'WORD_BANK', 'Terjemahkan: "Pesan hotel untuk dua malam"', '["Book","a","hotel","for","two","nights"]'::jsonb, 'Book a hotel for two nights'),
('travel-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Selamat jalan!"', null, 'Have a safe trip!'),
('travel-1', 'MULTIPLE_CHOICE', 'Apa arti "Boarding pass"?', '["Paspor","Tiket masuk pesawat","KTP","SIM"]'::jsonb, 'Tiket masuk pesawat'),
('restaurant-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Tagihan/Bon"', '["Menu","Bill","Order","Receipt"]'::jsonb, 'Bill'),
('restaurant-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Pelayan (Pria)"', '["Chef","Waitress","Waiter","Manager"]'::jsonb, 'Waiter'),
('restaurant-1', 'WORD_BANK', 'Terjemahkan: "Boleh minta menunya?"', '["Can","I","have","the","menu,","please?"]'::jsonb, 'Can I have the menu, please?'),
('restaurant-1', 'WORD_BANK', 'Terjemahkan: "Makanan ini sangat pedas"', '["This","food","is","very","spicy","sweet"]'::jsonb, 'This food is very spicy'),
('restaurant-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya ingin pesan steak"', null, 'I want to order a steak'),
('restaurant-1', 'MULTIPLE_CHOICE', 'Rasa gula adalah...', '["Salty","Spicy","Bitter","Sweet"]'::jsonb, 'Sweet'),
('restaurant-1', 'WORD_BANK', 'Terjemahkan: "Tolong tagihannya"', '["The","bill,","please","menu,","order"]'::jsonb, 'The bill, please'),
('restaurant-1', 'WORD_BANK', 'Terjemahkan: "Apakah ada meja kosong?"', '["Is","there","an","empty","table?","chair"]'::jsonb, 'Is there an empty table?'),
('restaurant-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Lezat sekali"', null, 'Very delicious'),
('restaurant-1', 'MULTIPLE_CHOICE', 'Apa arti "Beverage"?', '["Makanan ringan","Minuman","Makanan utama","Pencuci mulut"]'::jsonb, 'Minuman'),
('shopping-1', 'MULTIPLE_CHOICE', 'Bagaimana mengatakan "Berapa harganya?"', '["How many?","How much?","How long?","How old?"]'::jsonb, 'How much?'),
('shopping-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Uang tunai"', '["Credit card","Debit","Cash","Coin"]'::jsonb, 'Cash'),
('shopping-1', 'WORD_BANK', 'Terjemahkan: "Ini terlalu mahal"', '["This","is","too","expensive","cheap","good"]'::jsonb, 'This is too expensive'),
('shopping-1', 'WORD_BANK', 'Terjemahkan: "Bisa pakai kartu kredit?"', '["Can","I","pay","by","credit","card?"]'::jsonb, 'Can I pay by credit card?'),
('shopping-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya hanya melihat-lihat"', null, 'I am just looking'),
('shopping-1', 'MULTIPLE_CHOICE', 'Lawan kata "Expensive" adalah...', '["Rich","Poor","Cheap","Hard"]'::jsonb, 'Cheap'),
('shopping-1', 'WORD_BANK', 'Terjemahkan: "Apakah ada diskon?"', '["Is","there","a","discount?","sale?","free"]'::jsonb, 'Is there a discount?'),
('shopping-1', 'WORD_BANK', 'Terjemahkan: "Saya akan membelinya"', '["I","will","buy","it","sell","take"]'::jsonb, 'I will buy it'),
('shopping-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Di mana kamar pas?"', null, 'Where is the fitting room?'),
('shopping-1', 'MULTIPLE_CHOICE', 'Apa arti "Receipt"?', '["Resep masakan","Struk belanja","Uang kembali","Diskon"]'::jsonb, 'Struk belanja'),
('health-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Sakit"', '["Healthy","Sick","Strong","Well"]'::jsonb, 'Sick'),
('health-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Obat"', '["Drug","Medicine","Pill","Syrup"]'::jsonb, 'Medicine'),
('health-1', 'WORD_BANK', 'Terjemahkan: "Kepala saya sakit (Sakit kepala)"', '["I","have","a","headache","stomachache","fever"]'::jsonb, 'I have a headache'),
('health-1', 'WORD_BANK', 'Terjemahkan: "Anda harus pergi ke dokter"', '["You","should","go","to","the","doctor"]'::jsonb, 'You should go to the doctor'),
('health-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya merasa tidak enak badan"', null, 'I feel unwell'),
('health-1', 'MULTIPLE_CHOICE', 'Jika suhu tubuhmu tinggi, kamu mengalami...', '["Cough","Cold","Fever","Headache"]'::jsonb, 'Fever'),
('health-1', 'WORD_BANK', 'Terjemahkan: "Tarik napas dalam-dalam"', '["Take","a","deep","breath","breathe","slow"]'::jsonb, 'Take a deep breath'),
('health-1', 'WORD_BANK', 'Terjemahkan: "Di mana rumah sakit terdekat?"', '["Where","is","the","nearest","hospital?"]'::jsonb, 'Where is the nearest hospital?'),
('health-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Minum obatmu"', null, 'Take your medicine'),
('health-1', 'MULTIPLE_CHOICE', 'Apa arti "Ambulance"?', '["Mobil polisi","Pemadam kebakaran","Ambulans","Taksi"]'::jsonb, 'Ambulans'),
('hobbies-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Bermain sepak bola"', '["Play tennis","Play football","Play chess","Swim"]'::jsonb, 'Play football'),
('hobbies-1', 'MULTIPLE_CHOICE', 'Pilih terjemahan "Membaca buku"', '["Read books","Write books","Buy books","Sell books"]'::jsonb, 'Read books'),
('hobbies-1', 'WORD_BANK', 'Terjemahkan: "Hobi saya adalah melukis"', '["My","hobby","is","painting","drawing","singing"]'::jsonb, 'My hobby is painting'),
('hobbies-1', 'WORD_BANK', 'Terjemahkan: "Mereka suka menonton film"', '["They","like","watching","movies","TV","playing"]'::jsonb, 'They like watching movies'),
('hobbies-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Berenang di kolam"', null, 'Swimming in the pool'),
('hobbies-1', 'MULTIPLE_CHOICE', 'Hobi merawat tanaman disebut...', '["Cooking","Baking","Gardening","Reading"]'::jsonb, 'Gardening'),
('hobbies-1', 'WORD_BANK', 'Terjemahkan: "Bermain gitar"', '["Playing","the","guitar","piano","drum"]'::jsonb, 'Playing the guitar'),
('hobbies-1', 'WORD_BANK', 'Terjemahkan: "Kami suka bersepeda di pagi hari"', '["We","like","cycling","in","the","morning"]'::jsonb, 'We like cycling in the morning'),
('hobbies-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Mendengarkan musik"', null, 'Listening to music'),
('hobbies-1', 'MULTIPLE_CHOICE', 'Apa arti "Photography"?', '["Melukis","Memotret","Menyanyi","Menari"]'::jsonb, 'Memotret'),
('business-1', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Rapat"?', '["Gathering","Party","Meeting","Briefing"]'::jsonb, 'Meeting'),
('business-1', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Tenggat waktu"?', '["Timeline","Deadline","Schedule","Goal"]'::jsonb, 'Deadline'),
('business-1', 'WORD_BANK', 'Terjemahkan: "Saya ada rapat jam 2"', '["I","have","a","meeting","at","2"]'::jsonb, 'I have a meeting at 2'),
('business-1', 'WORD_BANK', 'Terjemahkan: "Rekan kerja saya sangat kooperatif"', '["My","colleague","is","very","cooperative","lazy"]'::jsonb, 'My colleague is very cooperative'),
('business-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Proyek ini penting"', null, 'This project is important'),
('business-1', 'MULTIPLE_CHOICE', 'Orang yang memimpin perusahaan disebut...', '["Employee","Client","Customer","CEO"]'::jsonb, 'CEO'),
('business-1', 'WORD_BANK', 'Terjemahkan: "Kita harus mencapai target"', '["We","must","achieve","the","target","miss"]'::jsonb, 'We must achieve the target'),
('business-1', 'WORD_BANK', 'Terjemahkan: "Bisakah kita menjadwalkan ulang?"', '["Can","we","reschedule?","cancel?","delay?"]'::jsonb, 'Can we reschedule?'),
('business-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Tolong kirimkan laporannya"', null, 'Please send the report'),
('business-1', 'MULTIPLE_CHOICE', 'Apa arti "Promotion"?', '["Penurunan pangkat","Promosi/Kenaikan jabatan","Pecat","Mutasi"]'::jsonb, 'Promosi/Kenaikan jabatan'),
('emails-1', 'MULTIPLE_CHOICE', 'Bagaimana menulis "Dengan hormat" (formal)?', '["Dear Sir/Madam,","Hi guys,","What''s up,","Hello,"]'::jsonb, 'Dear Sir/Madam,'),
('emails-1', 'MULTIPLE_CHOICE', 'Apa arti "Attached"?', '["Terpisah","Terlampir","Terhapus","Terkirim"]'::jsonb, 'Terlampir'),
('emails-1', 'WORD_BANK', 'Terjemahkan: "Tolong temukan dokumen terlampir"', '["Please","find","the","attached","document","file"]'::jsonb, 'Please find the attached document'),
('emails-1', 'WORD_BANK', 'Terjemahkan: "Saya menantikan balasan Anda"', '["I","look","forward","to","your","reply"]'::jsonb, 'I look forward to your reply'),
('emails-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Salam hormat" (Penutup email)', null, 'Sincerely'),
('emails-1', 'MULTIPLE_CHOICE', 'Kepanjangan dari "ASAP" adalah...', '["As Soon As Possible","As Slow As Possible","As Sweet As Pie","As Simple As Possible"]'::jsonb, 'As Soon As Possible'),
('emails-1', 'WORD_BANK', 'Terjemahkan: "Mengenai pertemuan kita besok"', '["Regarding","our","meeting","tomorrow","yesterday"]'::jsonb, 'Regarding our meeting tomorrow'),
('emails-1', 'WORD_BANK', 'Terjemahkan: "Tolong teruskan email ini ke tim"', '["Please","forward","this","email","to","the","team"]'::jsonb, 'Please forward this email to the team'),
('emails-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "CC ke manajer saya"', null, 'CC to my manager'),
('emails-1', 'MULTIPLE_CHOICE', 'Apa arti "Subject" dalam email?', '["Pelajaran","Subjek","Judul/Topik Email","Isi"]'::jsonb, 'Judul/Topik Email'),
('interview-1', 'MULTIPLE_CHOICE', 'Apa terjemahan dari "Wawancara"?', '["Meeting","Interview","Test","Exam"]'::jsonb, 'Interview'),
('interview-1', 'MULTIPLE_CHOICE', 'Apa arti "Resume"?', '["Kesimpulan","Lanjutkan","Daftar Riwayat Hidup / CV","Istirahat"]'::jsonb, 'Daftar Riwayat Hidup / CV'),
('interview-1', 'WORD_BANK', 'Terjemahkan: "Saya punya pengalaman 5 tahun"', '["I","have","5","years","of","experience"]'::jsonb, 'I have 5 years of experience'),
('interview-1', 'WORD_BANK', 'Terjemahkan: "Apa kekuatan terbesar Anda?"', '["What","is","your","greatest","strength?","weakness?"]'::jsonb, 'What is your greatest strength?'),
('interview-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya cepat belajar"', null, 'I am a fast learner'),
('interview-1', 'MULTIPLE_CHOICE', 'Lawan dari kekuatan ("Strength") adalah...', '["Skill","Weakness","Power","Talent"]'::jsonb, 'Weakness'),
('interview-1', 'WORD_BANK', 'Terjemahkan: "Saya tertarik dengan posisi ini"', '["I","am","interested","in","this","position","job"]'::jsonb, 'I am interested in this position'),
('interview-1', 'WORD_BANK', 'Terjemahkan: "Kapan saya bisa mulai bekerja?"', '["When","can","I","start","working?","job"]'::jsonb, 'When can I start working?'),
('interview-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Terima kasih atas waktunya"', null, 'Thank you for your time'),
('interview-1', 'MULTIPLE_CHOICE', 'Jika Anda diterima kerja, Anda berarti...', '["Fired","Hired","Retired","Tired"]'::jsonb, 'Hired'),
('tech-1', 'MULTIPLE_CHOICE', 'Apa arti "Download"?', '["Mengunggah","Mengunduh","Menghapus","Menyimpan"]'::jsonb, 'Mengunduh'),
('tech-1', 'MULTIPLE_CHOICE', 'Kutu dalam program perangkat lunak disebut...', '["Virus","Bug","Worm","Fly"]'::jsonb, 'Bug'),
('tech-1', 'WORD_BANK', 'Terjemahkan: "Aplikasi ini sangat lambat"', '["This","app","is","very","slow","fast"]'::jsonb, 'This app is very slow'),
('tech-1', 'WORD_BANK', 'Terjemahkan: "Tolong mulai ulang komputermu"', '["Please","restart","your","computer","phone","turn"]'::jsonb, 'Please restart your computer'),
('tech-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kata sandi salah"', null, 'Incorrect password'),
('tech-1', 'MULTIPLE_CHOICE', 'Tempat menyimpan data di internet secara virtual disebut...', '["The Cloud","The Sun","The Box","The Drive"]'::jsonb, 'The Cloud'),
('tech-1', 'WORD_BANK', 'Terjemahkan: "WiFi tidak terhubung"', '["The","WiFi","is","not","connected","disconnected"]'::jsonb, 'The WiFi is not connected'),
('tech-1', 'WORD_BANK', 'Terjemahkan: "Tekan tombol perbarui (update)"', '["Press","the","update","button","screen","click"]'::jsonb, 'Press the update button'),
('tech-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Layar sentuh"', null, 'Touch screen'),
('tech-1', 'MULTIPLE_CHOICE', 'Mengunggah file ke internet disebut...', '["Download","Upload","Reload","Offload"]'::jsonb, 'Upload'),
('finance-1', 'MULTIPLE_CHOICE', 'Apa arti "Salary"?', '["Hutang","Gaji","Bonus","Pajak"]'::jsonb, 'Gaji'),
('finance-1', 'MULTIPLE_CHOICE', 'Akun di bank disebut...', '["Bank account","Bank note","Bank card","Bank book"]'::jsonb, 'Bank account'),
('finance-1', 'WORD_BANK', 'Terjemahkan: "Saya ingin mentransfer uang"', '["I","want","to","transfer","some","money"]'::jsonb, 'I want to transfer some money'),
('finance-1', 'WORD_BANK', 'Terjemahkan: "Pajaknya tinggi sekali"', '["The","tax","is","very","high","low"]'::jsonb, 'The tax is very high'),
('finance-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Pasar saham"', null, 'Stock market'),
('finance-1', 'MULTIPLE_CHOICE', 'Jika Anda meminjam uang dari bank, Anda memiliki...', '["Investment","Debt","Profit","Savings"]'::jsonb, 'Debt'),
('finance-1', 'WORD_BANK', 'Terjemahkan: "Berapa saldo saya?"', '["What","is","my","balance?","money?","cash"]'::jsonb, 'What is my balance?'),
('finance-1', 'WORD_BANK', 'Terjemahkan: "Harga sahamnya naik"', '["The","stock","price","is","going","up"]'::jsonb, 'The stock price is going up'),
('finance-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Bebas finansial"', null, 'Financial freedom'),
('finance-1', 'MULTIPLE_CHOICE', 'Apa arti "Investment"?', '["Pengeluaran","Pendapatan","Investasi","Bunga"]'::jsonb, 'Investasi'),
('past-tense-1', 'MULTIPLE_CHOICE', 'Bentuk lampau dari "Go" adalah...', '["Goed","Went","Gone","Going"]'::jsonb, 'Went'),
('past-tense-1', 'MULTIPLE_CHOICE', 'Bentuk lampau dari "Eat" adalah...', '["Eated","Ate","Eaten","Eating"]'::jsonb, 'Ate'),
('past-tense-1', 'WORD_BANK', 'Terjemahkan: "Saya melihat dia kemarin"', '["I","saw","him","yesterday","see","today"]'::jsonb, 'I saw him yesterday'),
('past-tense-1', 'WORD_BANK', 'Terjemahkan: "Mereka bahagia tadi malam"', '["They","were","happy","last","night","was"]'::jsonb, 'They were happy last night'),
('past-tense-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya pergi ke sekolah"', null, 'I went to school'),
('past-tense-1', 'MULTIPLE_CHOICE', 'Pilih kata yang tepat: "She ___ not know"', '["do","does","did","doing"]'::jsonb, 'did'),
('past-tense-1', 'WORD_BANK', 'Terjemahkan: "Apakah kamu tidur nyenyak?"', '["Did","you","sleep","well?","Do","slept"]'::jsonb, 'Did you sleep well?'),
('past-tense-1', 'WORD_BANK', 'Terjemahkan: "Kami membeli mobil baru"', '["We","bought","a","new","car","buy"]'::jsonb, 'We bought a new car'),
('past-tense-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Dia (perempuan) menulis surat"', null, 'She wrote a letter'),
('past-tense-1', 'MULTIPLE_CHOICE', 'Bentuk lampau dari "Is" adalah...', '["Are","Was","Were","Been"]'::jsonb, 'Was'),
('future-tense-1', 'MULTIPLE_CHOICE', 'Pilih kata untuk mengekspresikan masa depan', '["Was","Will","Did","Had"]'::jsonb, 'Will'),
('future-tense-1', 'MULTIPLE_CHOICE', '"Going to" memiliki arti yang sama dengan...', '["Want to","Will","Used to","Have to"]'::jsonb, 'Will'),
('future-tense-1', 'WORD_BANK', 'Terjemahkan: "Saya akan pergi besok"', '["I","will","go","tomorrow","went","today"]'::jsonb, 'I will go tomorrow'),
('future-tense-1', 'WORD_BANK', 'Terjemahkan: "Dia akan segera tiba"', '["He","is","going","to","arrive","soon"]'::jsonb, 'He is going to arrive soon'),
('future-tense-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Kami tidak akan menyerah"', null, 'We will not give up'),
('future-tense-1', 'MULTIPLE_CHOICE', 'Pilih susunan yang benar: "They ___ travel next week"', '["will","are will","willing","would"]'::jsonb, 'will'),
('future-tense-1', 'WORD_BANK', 'Terjemahkan: "Akankah hujan nanti?"', '["Will","it","rain","later?","is","raining"]'::jsonb, 'Will it rain later?'),
('future-tense-1', 'WORD_BANK', 'Terjemahkan: "Saya pasti akan membantumu"', '["I","will","definitely","help","you","probably"]'::jsonb, 'I will definitely help you'),
('future-tense-1', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Saya akan menjadi dokter"', null, 'I will be a doctor'),
('future-tense-1', 'MULTIPLE_CHOICE', 'Singkatan dari "I will" adalah...', '["I''ll","I''m","I''ve","I''d"]'::jsonb, 'I''ll'),
('idioms-1', 'MULTIPLE_CHOICE', 'Apa arti idiom "Piece of cake"?', '["Sepotong kue","Sangat mudah","Sangat sulit","Makanan enak"]'::jsonb, 'Sangat mudah'),
('idioms-1', 'MULTIPLE_CHOICE', 'Apa arti "Break a leg"?', '["Patahkan kaki","Semoga berhasil","Celaka","Berhenti"]'::jsonb, 'Semoga berhasil'),
('idioms-1', 'WORD_BANK', 'Terjemahkan idiom: "Merasa kurang sehat" (Under the weather)', '["Feeling","under","the","weather","cloud","rain"]'::jsonb, 'Feeling under the weather'),
('idioms-1', 'WORD_BANK', 'Terjemahkan idiom: "Membocorkan rahasia" (Spill the beans)', '["Spill","the","beans","tea","coffee","secrets"]'::jsonb, 'Spill the beans'),
('idioms-1', 'TRANSLATION', 'Ketik idiom "Sekali seumur hidup" (Once in a blue moon)', null, 'Once in a blue moon'),
('idioms-1', 'MULTIPLE_CHOICE', 'Idiom "Bite the bullet" berarti...', '["Menggigit peluru","Menghadapi situasi sulit dengan berani","Marah besar","Takut"]'::jsonb, 'Menghadapi situasi sulit dengan berani'),
('idioms-1', 'WORD_BANK', 'Terjemahkan idiom: "Sangat mahal" (Cost an arm and a leg)', '["It","costs","an","arm","and","a","leg"]'::jsonb, 'It costs an arm and a leg'),
('idioms-1', 'WORD_BANK', 'Terjemahkan idiom: "Jangan menilai buku dari sampulnya"', '["Don''t","judge","a","book","by","its","cover"]'::jsonb, 'Don''t judge a book by its cover'),
('idioms-1', 'TRANSLATION', 'Ketik idiom "Sama-sama" (We are in the same boat)', null, 'We are in the same boat'),
('idioms-1', 'MULTIPLE_CHOICE', 'Apa arti "Hit the sack"?', '["Memukul karung","Pergi tidur","Bekerja keras","Berolahraga"]'::jsonb, 'Pergi tidur'),
('slang-1', 'MULTIPLE_CHOICE', 'Apa arti slang "Chill"?', '["Dingin","Santai","Marah","Cepat"]'::jsonb, 'Santai'),
('slang-1', 'MULTIPLE_CHOICE', 'Apa arti "Hang out"?', '["Menggantung di luar","Nongkrong","Keluar dari ruangan","Jemur pakaian"]'::jsonb, 'Nongkrong'),
('slang-1', 'WORD_BANK', 'Susun kalimat: "Ada apa?" (What''s up?)', '["What''s","up?","down?","going","how"]'::jsonb, 'What''s up?'),
('slang-1', 'WORD_BANK', 'Susun kalimat: "Itu keren banget" (That''s sick/dope)', '["That''s","dope","sick","ill","healthy"]'::jsonb, 'That''s dope'),
('slang-1', 'TRANSLATION', 'Ketik slang "Menghilang tiba-tiba tanpa kabar"', null, 'Ghosting'),
('slang-1', 'MULTIPLE_CHOICE', 'Apa arti slang "Salty"?', '["Asin","Marah/Kesal","Manis","Lucu"]'::jsonb, 'Marah/Kesal'),
('slang-1', 'WORD_BANK', 'Susun kalimat: "Santai saja bung"', '["Just","chill","out","bro","man"]'::jsonb, 'Just chill out bro'),
('slang-1', 'WORD_BANK', 'Susun kalimat: "Gue nggak peduli" (I don''t give a damn)', '["I","don''t","give","a","damn","care","shit"]'::jsonb, 'I don''t give a damn'),
('slang-1', 'TRANSLATION', 'Ketik slang "Sangat luar biasa/Keren" (Lit)', null, 'Lit'),
('slang-1', 'MULTIPLE_CHOICE', 'Apa arti "FOMO"?', '["Fear Of Missing Out","For Our Mother Only","Fast Or Move Over","Fear Of Making Options"]'::jsonb, 'Fear Of Missing Out'),
('conditionals-1', 'MULTIPLE_CHOICE', 'Lengkapi: "If it rains, I ___ stay at home"', '["will","would","had","am"]'::jsonb, 'will'),
('conditionals-1', 'MULTIPLE_CHOICE', 'Lengkapi: "If I were you, I ___ do that"', '["will not","would not","am not","do not"]'::jsonb, 'would not'),
('conditionals-1', 'WORD_BANK', 'Terjemahkan: "Jika aku punya uang, aku akan membelinya"', '["If","I","had","money,","I","would","buy","it"]'::jsonb, 'If I had money, I would buy it'),
('conditionals-1', 'WORD_BANK', 'Terjemahkan: "Jika kamu belajar, kamu akan lulus"', '["If","you","study,","you","will","pass","fail"]'::jsonb, 'If you study, you will pass'),
('conditionals-1', 'TRANSLATION', 'Ketik: "Jika aku jadi burung, aku akan terbang"', null, 'If I were a bird, I would fly'),
('conditionals-1', 'MULTIPLE_CHOICE', 'Conditional type 3: "If I had known, I ___ gone"', '["will have","would have","would had","will had"]'::jsonb, 'would have'),
('conditionals-1', 'WORD_BANK', 'Terjemahkan: "Seandainya aku tidak terlambat"', '["If","only","I","hadn''t","been","late"]'::jsonb, 'If only I hadn''t been late'),
('conditionals-1', 'WORD_BANK', 'Terjemahkan: "Kamu akan sakit jika kamu makan itu"', '["You","will","get","sick","if","you","eat","that"]'::jsonb, 'You will get sick if you eat that'),
('conditionals-1', 'TRANSLATION', 'Ketik: "Apa yang akan kamu lakukan jika kamu menang?"', null, 'What would you do if you won?'),
('conditionals-1', 'MULTIPLE_CHOICE', '"Unless" memiliki arti yang mirip dengan...', '["If only","If not","Even if","As if"]'::jsonb, 'If not'),
('commute-jkt', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Macet"?', '["Traffic light","Traffic jam","Traffic cone","Traffic stop"]'::jsonb, 'Traffic jam'),
('commute-jkt', 'MULTIPLE_CHOICE', 'Jam sibuk berangkat/pulang kerja disebut...', '["Busy hour","Rush hour","Hurry hour","Fast hour"]'::jsonb, 'Rush hour'),
('commute-jkt', 'WORD_BANK', 'Terjemahkan: "Saya naik KRL (Commuter Line) ke kantor"', '["I","take","the","commuter","line","to","the","office"]'::jsonb, 'I take the commuter line to the office'),
('commute-jkt', 'WORD_BANK', 'Terjemahkan: "Pesan ojek online (Gojek/Grab)"', '["Order","an","online","motorcycle","taxi","ojol"]'::jsonb, 'Order an online motorcycle taxi'),
('commute-jkt', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Keretanya sangat penuh"', null, 'The train is very crowded'),
('commute-jkt', 'MULTIPLE_CHOICE', 'Istilah untuk pindah jalur kereta di Stasiun Manggarai...', '["Transit","Transform","Transport","Transmit"]'::jsonb, 'Transit'),
('commute-jkt', 'WORD_BANK', 'Terjemahkan: "Saya terjebak macet parah di Sudirman"', '["I","am","stuck","in","bad","traffic","in","Sudirman"]'::jsonb, 'I am stuck in bad traffic in Sudirman'),
('commute-jkt', 'WORD_BANK', 'Terjemahkan: "Hati-hati copet di halte busway"', '["Beware","of","pickpockets","at","the","bus","stop"]'::jsonb, 'Beware of pickpockets at the bus stop'),
('commute-jkt', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Jalan tol ditutup"', null, 'The toll road is closed'),
('commute-jkt', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Trotoar"?', '["Street","Sidewalk","Highway","Alley"]'::jsonb, 'Sidewalk'),
('streetfood-jkt', 'MULTIPLE_CHOICE', 'Bagaimana bilang "Minta dibungkus (takeaway)"?', '["Wrap it","Take away","Bring it","Put in bag"]'::jsonb, 'Take away'),
('streetfood-jkt', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Pedas"?', '["Sweet","Salty","Spicy","Sour"]'::jsonb, 'Spicy'),
('streetfood-jkt', 'WORD_BANK', 'Terjemahkan: "Bang, nasi goreng satu, tidak pakai pedas"', '["One","fried","rice,","please,","not","spicy","no"]'::jsonb, 'One fried rice, please, not spicy'),
('streetfood-jkt', 'WORD_BANK', 'Terjemahkan: "Makan di sini atau dibungkus?"', '["For","here","or","to","go?","eat","take"]'::jsonb, 'For here or to go?'),
('streetfood-jkt', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Warung tenda jalanan"', null, 'Street food stall'),
('streetfood-jkt', 'MULTIPLE_CHOICE', 'Pedagang kaki lima dalam bahasa Inggris disebut...', '["Foot trader","Street vendor","Road seller","Walking shop"]'::jsonb, 'Street vendor'),
('streetfood-jkt', 'WORD_BANK', 'Terjemahkan: "Krupuk ini alot (tidak renyah)"', '["This","cracker","is","stale","not","crispy","tough"]'::jsonb, 'This cracker is stale'),
('streetfood-jkt', 'WORD_BANK', 'Terjemahkan: "Jangan pakai seledri dan daun bawang"', '["No","celery","and","spring","onions,","please"]'::jsonb, 'No celery and spring onions, please'),
('streetfood-jkt', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Es teh manis"', null, 'Sweet iced tea'),
('streetfood-jkt', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Kenyang"?', '["Empty","Hungry","Full","Done"]'::jsonb, 'Full'),
('social-jkt', 'MULTIPLE_CHOICE', 'Kata gaul Jaksel "Which is" artinya apa?', '["Yang mana","Di mana","Siapa yang","Kapan"]'::jsonb, 'Yang mana'),
('social-jkt', 'MULTIPLE_CHOICE', 'Apa arti kata "Literally"?', '["Mungkin saja","Secara harfiah","Kira-kira","Bukan main"]'::jsonb, 'Secara harfiah'),
('social-jkt', 'WORD_BANK', 'Terjemahkan slang: "Tempat nongkrong ini sangat PW (pewe)"', '["This","hangout","spot","is","so","cozy","comfortable"]'::jsonb, 'This hangout spot is so cozy'),
('social-jkt', 'WORD_BANK', 'Terjemahkan: "Gue bener-bener butuh es kopi sekarang"', '["I","literally","need","an","iced","coffee","right","now"]'::jsonb, 'I literally need an iced coffee right now'),
('social-jkt', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Mari kita patungan (split the bill)"', null, 'Let''s split the bill'),
('social-jkt', 'MULTIPLE_CHOICE', 'Istilah untuk teman nongkrong / lingkaran pertemanan...', '["Circle","Group","Team","Band"]'::jsonb, 'Circle'),
('social-jkt', 'WORD_BANK', 'Terjemahkan: "Harga kopinya overpriced (kemahalan)"', '["The","coffee","price","is","overpriced","too","expensive"]'::jsonb, 'The coffee price is overpriced'),
('social-jkt', 'WORD_BANK', 'Terjemahkan: "Akhir pekan ini kita nongkrong di Senopati"', '["Let''s","hang","out","in","Senopati","this","weekend"]'::jsonb, 'Let''s hang out in Senopati this weekend'),
('social-jkt', 'TRANSLATION', 'Ketik slang: "Caper (Seeking attention)"', null, 'Attention seeker'),
('social-jkt', 'MULTIPLE_CHOICE', 'Apa itu "Hidden Gem"?', '["Permata palsu","Tempat bagus yang tersembunyi","Batu akik","Tempat mahal"]'::jsonb, 'Tempat bagus yang tersembunyi'),
('housing-jkt', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris yang paling mendekati "Kos-kosan"?', '["Hotel","Boarding house","Apartment","Mansion"]'::jsonb, 'Boarding house'),
('housing-jkt', 'MULTIPLE_CHOICE', 'Uang sewa bulanan disebut...', '["Monthly rent","Monthly fee","Monthly pay","Monthly tax"]'::jsonb, 'Monthly rent'),
('housing-jkt', 'WORD_BANK', 'Terjemahkan: "AC di kamar saya rusak"', '["The","AC","in","my","room","is","broken"]'::jsonb, 'The AC in my room is broken'),
('housing-jkt', 'WORD_BANK', 'Terjemahkan: "Apakah biaya sewa sudah termasuk listrik?"', '["Does","the","rent","include","electricity?","water?"]'::jsonb, 'Does the rent include electricity?'),
('housing-jkt', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Bapak kos (Pemilik kos pria)"', null, 'Landlord'),
('housing-jkt', 'MULTIPLE_CHOICE', 'Apa sebutan untuk ibu kos (Pemilik kos wanita)?', '["Landwoman","Landlady","Housemom","Hostess"]'::jsonb, 'Landlady'),
('housing-jkt', 'WORD_BANK', 'Terjemahkan: "Kamar mandi dalam"', '["En-suite","bathroom","inside","toilet","room"]'::jsonb, 'En-suite bathroom'),
('housing-jkt', 'WORD_BANK', 'Terjemahkan: "Saya akan pindah kos bulan depan"', '["I","will","move","out","next","month"]'::jsonb, 'I will move out next month'),
('housing-jkt', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Tagihan air"', null, 'Water bill'),
('housing-jkt', 'MULTIPLE_CHOICE', 'Aturan jam malam di kos-kosan disebut...', '["Curfew","Sleep time","Night rule","Lock down"]'::jsonb, 'Curfew'),
('office-jkt', 'MULTIPLE_CHOICE', 'Apa singkatan dari WFO?', '["Work For Office","Work From Office","Walk From Office","Work Fast Okay"]'::jsonb, 'Work From Office'),
('office-jkt', 'MULTIPLE_CHOICE', 'Apa bahasa Inggris dari "Lembur"?', '["Overwork","Overtime","Extra time","Late work"]'::jsonb, 'Overtime'),
('office-jkt', 'WORD_BANK', 'Terjemahkan: "Saya kerja sistem hybrid (campur WFO & WFH)"', '["I","work","on","a","hybrid","system","setup"]'::jsonb, 'I work on a hybrid setup'),
('office-jkt', 'WORD_BANK', 'Terjemahkan: "Gaji masuk akhir bulan"', '["Salary","comes","in","at","the","end","of","the","month"]'::jsonb, 'Salary comes in at the end of the month'),
('office-jkt', 'TRANSLATION', 'Ketik dalam bahasa Inggris: "Tanggal tua (Keuangan menipis)"', null, 'Broke'),
('office-jkt', 'MULTIPLE_CHOICE', 'Pekerja komuter yang setiap hari bolak-balik (misal dari Bekasi ke Jakarta) disebut...', '["Traveler","Commuter","Passenger","Driver"]'::jsonb, 'Commuter'),
('office-jkt', 'WORD_BANK', 'Terjemahkan: "Rapatnya diundur ke jam 3"', '["The","meeting","is","pushed","back","to","3","PM"]'::jsonb, 'The meeting is pushed back to 3 PM'),
('office-jkt', 'WORD_BANK', 'Terjemahkan: "Cari makan siang yuk bareng anak kantor"', '["Let''s","grab","lunch","with","the","office","colleagues"]'::jsonb, 'Let''s grab lunch with the office colleagues'),
('office-jkt', 'TRANSLATION', 'Ketik slang kantor: "ASAP (Secepat mungkin)"', null, 'As soon as possible'),
('office-jkt', 'MULTIPLE_CHOICE', 'Apa istilah untuk berhenti dari pekerjaan (Resign)?', '["Quit","Leave","Retire","Semua benar (Tergantung konteks)"]'::jsonb, 'Semua benar (Tergantung konteks)');